version: "3.4"
services:
  influx:
    container_name: influx
    hostname: influx
    image: influxdb:2.7.5-alpine
    ports:
      - "8086:8086"
    volumes:
      - "/home/ubuntu/db/influx:/var/lib/influxdb2"
    restart: always
