export RUST_LOG=main=debug
export KRKNC_BROKER_HOST=http://127.0.0.1:50051
export KRKNC_WEBHOOK_PATH=webhook
export KRKNC_WEBHOOK_PORT=80
export KRKNC_MQTT_TOPIC=kraken
export KRKNC_MQTT_CONFIG_PATH=${PWD}/config/rumqttd.toml
export KRKNC_WEBSOCKET_HOST=0.0.0.0:2794
export KRKNC_IBEACON_FILTER_DURATION_SEC=1
export KRKNC_IBEACON_ALLOWED_UUID_FILTER_PATH=${PWD}/config/allowed_uuids.yml
export KRKNC_SERIAL_DEVICE_NAME=brave_jig
export KRKNC_SERIAL_PORT=/dev/ttyACM0
export KRKNC_SERIAL_BAUDRATE=38400
export KRKNC_SERIAL_TIMEOUT_SEC=10
#export KRKNC_CAMERA_PORT=/dev/video0
export KRKNC_CAMERA_CAPTURE_INTERVAL_SEC=5

# Email Collector Settings
export KRKNC_EMAIL_HOST_ADDR=0.0.0.0
export KRKNC_EMAIL_SMTP_PORT=587
export KRKNC_EMAIL_MAX_MESSAGE_SIZE=10485760
export KRKNC_EMAIL_MAX_ATTACHMENT_SIZE=5242880
export KRKNC_EMAIL_DOMAIN=localhost
#export KRKNC_EMAIL_AUTH_REQUIRED=false
#export KRKNC_EMAIL_ALLOWED_SENDERS=trusted@example.com,admin@example.org
#export KRKNC_EMAIL_TLS_ENABLED=false
#export KRKNC_EMAIL_TLS_CERT_PATH=/path/to/cert.pem
#export KRKNC_EMAIL_TLS_KEY_PATH=/path/to/key.pem
#export KRKNC_EMAIL_TLS_REQUIRE=false